services:
  db:
    image: ankane/pgvector
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgvector
    ports:
      - "54369:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # Stores data outside the container to ensure persistence